theme:

site_name: PUM Companion Online Hub
site_description: >-
  Online Hub for PUM Companion: the app for solo RPG, storytelling, and journaling. Discover, create, and share your stories.
site_url: https://Unfolding-Machines.github.io/pumc-online-hub/
repo_url: https://github.com/Unfolding-Machines/pumc-online-hub/
repo_name: Unfolding-Machines/pumc-online-hub
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logos/pumc_icon_512.png  # Updated to use the new PUMC icon
  favicon: assets/logos/unfolding_machines.png  # Updated to use Unfolding Machines logo as favicon
  font:
    text: 'Merriweather'
    code: 'Fira Mono'
  palette:
    - scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
  language: en
  static_templates:
    - 404.html
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/custom.css
nav:
  - Welcome Page: index.md
  - About the Unfolding Machines: about-pum.md
  - Playing PUM:
      - Plot Tracks: plot-tracks.md
      - Plot Nodes: plot-nodes.md
      - Plot Focus: plot-focus.md
      - Oracles: oracles.md
      - Game Concepts: game-concepts.md
  - PUM Companion:
      - What is PUM Companion?: pum-companion.md
      - Dice Formula Expressions: dice-formulas.md
      - Random Tables: random-tables.md
      - Decks & Cards: decks-cards.md
      - Markdown Text Styling: markdown-styling.md
  - Information:
      - Get the games: get-the-games.md